---
- hosts: webservers
  become: yes
  tasks:
  - name:  java on ubuntu
    apt:
     name: "{{javaonubuntu}}"
     state: present
    when: ansible_os_family=="Debian"
  
  - name: java on redhat
    yum:
     name: "{{javaonredhat}}"
     state: present
    when: ansible_os_family=="RedHat" 