---
- hosts:  172.31.80.95
  become: yes
  tasks:
  - name: execute linux command
    command: hostname -f
    registerr: result

  - name: display result
    debug:
     msg: "{{result}}"



  - name: install git
    apt:
      name: git
      state: present
    when: result.stderr ==""
    
    
  - name: install tree
    apt: 
      name: tree
      state: present
    when: result.stderr !=""  
      