---
- hosts: webservers
  become: yes
  tasks:
  - name: install tree
    yum:
      name: tree
      statee: present
    ignore_errors: yes
    when: ansible_os_family=="RedHat"  
  - name: install git
    yum:
      name: git
      state: present
    when: ansible_os_family=="RedHat"

  
   



      
      