---
- hosts: ubuntuservers
  become : yes
  tasks:
  - name: install webserver on ubuntu
    apt:
      name: apache2
      start: present
    notify: restart webserver
    when: ansible_os_family=="Debian"
    
  - name: copy indexfile to node
    template:
      src: myindex.j2
      des: /var/www/html/index.html
    notify: restart webserver
    when: ansible_os_family=="Debian"
    
  handlers:
    - name: restart webserver
      service:
        name: apache2
        state: restarted
