---
- hosts: appservers
  become: yes
  tasks:
  - name: install tree
    yum:
     name: "{{item}}"
     state: present
     
    loop:
     - tree
     - wget
     - git
    when: ansible_os_family=="Debian"
