---
- hosts: 172.31.80.95
  become: yes
  tasks:

- name: install wget
  apt:
    name: wget
    state: present
  tags: wget

- name: install git
  apt: 
    name: git
    state: present
  tags: git
  
- name: install tree
  apt:
    name: tree
    state: present
  tags: tree  

