---
- hosts: webservers
  become: yes
  vars:
    var1: radha
    var2: anu
    var3: naveena
  tasks:
    - name: display var1
      debug:
        msg: "{{var1}}"
        
    - name: display var2
      debug:
        msg: "{{var2}}"
    
    - name: display var3
      debug: 
        msg: "{{var3}}"  
        
