---
- hosts: all
  become: yes
  tasks:
  - name: install webserver on redhat
    yum:
     name: httpd
     state: present
  - name: start  the webserver on redhat
    service:
      name: httpd
      state: started

  - name: install webserver on ubuntu
     apt:
      name: apache2
      state: present
   - name: service the webserver on ubuntu
     service:
      name: apache2
      state: started


