---
- hosts: all
  become: yes
  tasks:
  - name: webserver on ubuntu16
    apt:
     name: apache2
     state: present

  - name: start webserver on ubuntu16
    service: 
     name: apache2
     state: started

  - name: install webserver on redhat8
    yum:
     name: httpd
     state: present

  - name: start webserver on redhat8
    service:
     name: httpd
     state: started