---
- hosts: all
  become: yes
  tasks:
  - name: webserver on ubuntu
    apt:
      name: apache2
      state: present  

  - name: start the webserver on ubuntu
    service:
      name: apache2
      state: started

  - name: webserver on redhat
    yum:
      name: httpd
      state: present
      
  - name: start webserver on redhat
    service:
      name: httpd
      state: started