---
- hosts: webservers 
  become: yes
  tasks:
  - name: webserver on ubuntu
    apt:
      name: "{webserveronubuntu}"
      state: present
    when: ansible_os_family=="Debian"
  - name: start the webserver on ubuntu
    service:
      name: "{webserveronubuntu}"
      state: started
    when: ansible_os_family=="Debian"

  - name: webserver on redhat
    yum:
      name: "{webserveronredhat}"
      state: present
    when: ansible_os_family=="RedHat"
      
  - name: start webserver on redhat
    service:
      name: "{webserveronredhat}"
      state: started
    when: ansible_os_family=="RedHat"