---
- hosts: webservers 
  become: yes
  tasks:
  - name: webserver on ubuntu
    apt:
      name: "webserver on ubuntu"
      state: present
    when: ansible_os_family=="Debian"
  - name: start the webserver on ubuntu
    service:
      name: "webserver on ubuntu"
      state: started
    when: ansible_os_family=="Debian"

  - name: webserver on redhat
    yum:
      name: "webserver on redhat"
      state: present
    when: ansible_os_family=="RedHat"
      
  - name: start webserver on redhat
    service:
      name: "webserver on redhat"
      state: started
    when: ansible_os_family=="RedHat"